apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx:12.0
    volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 4332
    volumes:
      - name: mypd
        PersistentVolumeClaim:
          claimName: pvc-name
        
