apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
     path: /mnd/disks/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpression:
          - key: kubernetes.io/hostname
            operator: In
            values: 
            - example-node
