apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 10G
  volumeMode: Filesystem
  storageClassName: storage-class-name
  accessModes:
    - ReadWriteOnce
